name = "prime_time"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["AJ Ianozi"]
maintainers = ["AJ Ianozi <aj@ianozi.com>"]
maintainers-logins = ["aj-ianozi"]

executables = ["prime_time"]


[build-switches]
"*".Ada_Version = "Ada2022"

[[depends-on]]
simple_components = "^4.62.0"
[[depends-on]]
json = "^5.0.3"
